security:
  sessions: never
spring:
  session:
    store-type: mongo
    mongo:
      collection-name: usersessions
  application:
    name: frontend
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/studentShowcase
server:
  port: 9001