logging:
  level:
    org.springframework.security: DEBUG
zuul:
  routes:
    ui:
      path: /**
      url: http://localhost:9001
      sensitive-headers:
    api:
      path: /api/**
      url: http://localhost:9000
      sensitive-headers: