logging:
  level:
    org.springframework.security: DEBUG
zuul:
  routes:
    ui:
      path: /*
      url: http://localhost:9001
      sensitive-headers:
#    admin:
#      url: http://localhost:8082
#      sensitive-headers:
#    resource:
#      url: http://localhost:9000
#      sensitive-headers: